module.exports = {
	$schema: "http://json.schemastore.org/prettierrc",
	plugins: ["@trivago/prettier-plugin-sort-imports", "prettier-plugin-tailwindcss"],
	arrowParens: "always",
	proseWrap: "always",
	quoteProps: "as-needed",
	useTabs: true,
	semi: true,
	tabWidth: 2,
	printWidth: 100,
	endOfLine: "auto",
	bracketSameLine: false,
	singleQuote: false,
	jsxSingleQuote: false,
	trailingComma: "all",
	bracketSpacing: true,
	importOrder: ["^(react|next)", "^@/(.*)$", "^[./]"],
	importOrderSeparation: true,
	importOrderSortSpecifiers: true,
};
